// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HSH1E0WxZlNdFHuVVYJHKD6x2oeZd1c',
    appId: '1:881757108961:web:e4f223b1407795b006d5a0',
    messagingSenderId: '881757108961',
    projectId: 'ekalgsrepo-db',
    authDomain: 'ekalgsrepo-db.firebaseapp.com',
    databaseURL: 'https://ekalgsrepo-db-default-rtdb.firebaseio.com',
    storageBucket: 'ekalgsrepo-db.appspot.com',
    measurementId: 'G-DGMJ7G5CEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwJNG9fm_VEztauUWk02LGkiAFAAuY90',
    appId: '1:881757108961:android:cf6780be596acc4d06d5a0',
    messagingSenderId: '881757108961',
    projectId: 'ekalgsrepo-db',
    databaseURL: 'https://ekalgsrepo-db-default-rtdb.firebaseio.com',
    storageBucket: 'ekalgsrepo-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYouqRJfK3Ih0R4_jXLbE2Qu4v18amio',
    appId: '1:881757108961:ios:186e85d53f75b33006d5a0',
    messagingSenderId: '881757108961',
    projectId: 'ekalgsrepo-db',
    databaseURL: 'https://ekalgsrepo-db-default-rtdb.firebaseio.com',
    storageBucket: 'ekalgsrepo-db.appspot.com',
    iosClientId: '881757108961-ddbuoj7o8dfquffoliucq326cv6vs7l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jaagran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYYouqRJfK3Ih0R4_jXLbE2Qu4v18amio',
    appId: '1:881757108961:ios:b14b0776bebfedd306d5a0',
    messagingSenderId: '881757108961',
    projectId: 'ekalgsrepo-db',
    databaseURL: 'https://ekalgsrepo-db-default-rtdb.firebaseio.com',
    storageBucket: 'ekalgsrepo-db.appspot.com',
    iosClientId: '881757108961-0cmhoo84h52av8j5su0iluj87hg0f1a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jaagran.RunnerTests',
  );
}
